const express = require('express')
const app = express()
require('dotenv').config()
const bcrypt = require('bcrypt')
const bodyparser = require('body-parser')
const cors = require('cors')
const fs = require('fs')
const { faker, fakerRO } = require('@faker-js/faker')
const { MongoClient } = require('mongodb')
const mysql = require('mysql2')
const path = require('path')
app.use(express.json())
app.use(express.static('public'))
app.use(express.urlencoded({ extended: true }))